### PR TITLE
expose default port 8080 of webapi container

### PR DESCRIPTION
**Pull request by daveyx**
see:
https://forum.metasfresh.org/t/docker-expose-default-port-of-webapi-container/323

### CODE REVIEW

**Comment by metas-jb** [comment]
Exposing the webapi container should not be necessary for general usage of the metasfresh-stack in docker.
Users shall change the `webui` exposed port as described [here](http://docs.metasfresh.org/installation_collection/EN/How_do_I_change_the_webui_ports_for_metasfresh_docker.html)

Check [https://forum.metasfresh.org/t/docker-expose-default-port-of-webapi-container/323?u=julian.bischof](https://forum.metasfresh.org/t/docker-expose-default-port-of-webapi-container/323?u=julian.bischof) for a more detailed explanation.

**Comment by metas-ts** [comment]
@metas-jb what if soneone actually wants to http to the webui-api ? 
e.g. to verify its build version via http://<web-api>:8080/info ?

I understand the we don't want to open ports for the end users if they don'T know (nor care) what to to with them, but maybe it makes sense to at least have this in the file but commented out, with an info...
wdyt?

**Comment by metas-jb** [comment]
@metas-ts 
In the (rare) case you want to access the webapi container directly you can expose the port "8080".
However, I'd suggest not to open this port by default for all users but only use it in a "if necessary" case.

If you want to make permanent changes on URLs (eg. http://myserver:8080/info) I'd suggest you add a new entry in the apache configs of the webui since it also acts as a proxy for api-requests: [metasfresh_webui.conf](https://github.com/metasfresh/metasfresh-docker/blob/master/webui/sources/configs/metasfresh_webui.conf) and [metasfresh_webui_ssl.conf](https://github.com/metasfresh/metasfresh-docker/blob/master/webui/sources/configs/metasfresh_webui_ssl.conf)
After performing a `docker-compose build` your changes will be applied and the requested URL will be available as eg. "http://myserver/info" (note the ommited "8080" since it's not necessary)

**Comment by daveyx** [comment]
@metas-jb i vote up for commenting out, could be useful. But then "expose" would not be enough, "ports" must be used then.

**Pull request closed without merging**
